// Generated by CoffeeScript 1.7.1
(function() {
  define(['angular', 'angular-route', 'angular-resource', 'angular-foundation', 'angular-images-loaded', 'angular-infinite-scroll', 'angular-masonry', 'angular-localforage', 'controllers', 'directives', 'services'], function(angular) {
    var app, dependencies;
    dependencies = ['ngResource', 'ngRoute', 'LocalForageModule', 'infinite-scroll', 'wu.masonry', 'Reddit2.controllers', 'Reddit2.directives', 'Reddit2.services'];
    app = angular.module("Reddit2", dependencies);
    return app;
  });

}).call(this);
