// Generated by CoffeeScript 1.7.1
(function() {
  define(['angular', 'services'], function(angular, services) {
    var module;
    module = angular.module('Reddit2.directives', ['Reddit2.services']);
    return module.directive('appName', [
      'name', function(name) {
        return function(scope, elm, attrs) {
          return elm.text(name);
        };
      }
    ]);
  });

}).call(this);
