// Generated by CoffeeScript 1.7.1
(function() {
  window.name = "NG_DEFER_BOOTSTRAP!";

  require.config({
    baseUrl: '',
    paths: {
      'app': 'js/app',
      'controllers': 'js/controllers',
      'directives': 'js/directives',
      'routes': 'js/routes',
      'services': 'js/services',
      'angular': 'components/angular/angular',
      'angular-resource': 'components/angular-resource/angular-resource',
      'angular-route': 'components/angular-route/angular-route',
      'bootstrap': 'components/bootstrap/dist/js/bootstrap.min',
      'imagesloaded': 'components/imagesloaded/imagesloaded.pkgd.min',
      'jquery': 'components/jquery/dist/jquery.min',
      'underscore': 'components/underscore/underscore-min'
    },
    shim: {
      'app': {
        deps: ['angular']
      },
      'angular': {
        exports: 'angular'
      },
      'angular-resource': {
        deps: ['angular']
      },
      'angular-route': {
        deps: ['angular']
      },
      'bootstrap': {
        deps: ['jquery']
      },
      'imagesloaded': {
        exports: 'imagesLoaded'
      },
      'underscore': {
        exports: '_'
      }
    },
    priority: ['angular'],
    deps: ['app']
  });

  require(['angular', 'app', 'routes'], function(angular, app) {
    return angular.element().ready(function() {
      return angular.resumeBootstrap([app['name']]);
    });
  });

}).call(this);
