// Generated by CoffeeScript 1.7.1
(function() {
  define(['angular', 'app'], function(angular, app) {
    app.config([
      "$routeProvider", function($routeProvider) {
        $routeProvider.when("/home", {
          templateUrl: "partials/feed.html",
          controller: "FeedController"
        });
        $routeProvider.when("/r/:subreddits", {
          templateUrl: "partials/feed.html",
          controller: "FeedController"
        });
        $routeProvider.when("/comments/:permalink*", {
          templateUrl: "partials/thread.html",
          controller: "ThreadController"
        });
        return $routeProvider.otherwise({
          redirectTo: "/home"
        });
      }
    ]);
    return app;
  });

}).call(this);
