// Generated by CoffeeScript 1.7.1
(function() {
  define(['angular'], function(angular) {
    var module;
    module = angular.module('Reddit2.services', []);
    return module.value('name', 'World');
  });

}).call(this);
