// Generated by CoffeeScript 1.7.1
(function() {
  define(['angular', 'underscore'], function(angular, _) {
    var module, safeText;
    module = angular.module('Reddit2.services', []);
    safeText = function(text) {
      var el;
      if (text == null) {
        text = "";
      }
      text = text.replace(/<!--\w+-->/, '');
      el = $('<div />').html(text);
      return $(el).text();
    };
    module.factory("Reddit", [
      '$http', '$sce', function($http, $sce) {
        var _Reddit;
        _Reddit = (function() {
          function _Reddit() {}

          _Reddit.prototype.items = [];

          _Reddit.prototype.loading = false;

          _Reddit.prototype.after = "";

          _Reddit.prototype.nextPage = function() {
            var url;
            if (this.loading) {
              return;
            }
            this.loading = true;
            url = "https://reddit.com/r/funny+pics+wtf+aww+adviceanimals/.json?after=" + this.after + "&jsonp=JSON_CALLBACK";
            return $http.jsonp(url).success((function(_this) {
              return function(data) {
                var item, items, _i, _item, _len;
                items = data.data.children;
                for (_i = 0, _len = items.length; _i < _len; _i++) {
                  item = items[_i];
                  _item = item.data;
                  _item.selftext_html = $sce.trustAsHtml(safeText(_item.selftext_html));
                  _this.items.push(_item);
                }
                _this.after = "t3_" + _this.items[_this.items.length - 1].id;
                return _this.loading = false;
              };
            })(this));
          };

          return _Reddit;

        })();
        return _Reddit;
      }
    ]);
    return module.factory("Thread", [
      '$http', '$sce', function($http, $sce) {
        var _Thread;
        _Thread = (function() {
          function _Thread(permalink) {
            this.comments = [];
            if (permalink[0] !== '/') {
              permalink = '/' + permalink;
            }
            this.url = "https://reddit.com" + permalink + ".json?jsonp=JSON_CALLBACK";
            this.fetch();
          }

          _Thread.prototype.fetch = function() {
            return $http.jsonp(this.url).success((function(_this) {
              return function(resp) {
                var comments, root, _ref, _ref1;
                root = resp;
                if (resp.length) {
                  root = resp[1];
                }
                comments = (root != null ? (_ref = root.data) != null ? _ref.children : void 0 : void 0) || (root != null ? (_ref1 = root.data) != null ? _ref1.replies : void 0 : void 0);
                comments = _.sortBy(comments, (function(c) {
                  return 1e5 - c.data.ups + c.data.downs;
                }));
                _this.op = resp[0].data.children[0].data;
                return _this.comments = comments;
              };
            })(this));
          };

          return _Thread;

        })();
        return _Thread;
      }
    ]);
  });

}).call(this);
